### PR TITLE
Convert to using ppx

### PR DESCRIPTION
**Pull request by rwmjones**
The patch series converts ocaml-gettext from camlp4 to ppx, thus allowing it to work with OCaml 4.08.

This patch series isn't quite "there" yet, but needs only a little help to get it over the line.  There are 11 failures in the test suite which I'll attach.

The first 5 patches are basically cleanup which can probably go upstream without too much controversy.  The final patch is the actual ppx conversion and that needs some more attention.

### CODE REVIEW

**Comment by rwmjones** [comment]
```
Version         : ocaml-gettext 0.3.7
OS              : Unix
Running tests ...
.......................................................................................................................................................................................FFFFFF........FFFFF
==============================================================================
Failure: Test ocaml-gettext:11:Compile OCaml code:6:invalid_format5.ml

error output of ocamlc -c -I ../libgettext-ocaml/ -I ../libgettext-stub-ocaml/ TestGettext.ml invalid_format5.ml
expected: "File \"invalid_format5.ml\", line 5, characters 29-45:\nError: This expression has type (int64 -> 'a, 'b, 'c, 'd, 'd, 'a) format6\n       but an expression was expected of type\n         (int -> 'e, 'f, 'g, 'g, 'g, 'e) format6\n"
but got: "File \"invalid_format5.ml\", line 5, characters 29-45:\n5 |   eprintf (fn_ \"%d category\" \"%Ld categories\" 1) 1\n                                 ^^^^^^^^^^^^^^^^\nError: This expression has type\n         (int -> 'a, int -> 'a) CamlinternalFormatBasics.precision\n       but an expression was expected of type\n         (int -> 'a, int64 -> 'b) CamlinternalFormatBasics.precision\n       Type int is not compatible with type int64 \n"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:11:Compile OCaml code:5:invalid_format4.ml

error output of ocamlc -c -I ../libgettext-ocaml/ -I ../libgettext-stub-ocaml/ TestGettext.ml invalid_format4.ml
expected: "File \"invalid_format4.ml\", line 5, characters 20-21:\nError: This expression has type int but an expression was expected of type\n         bool\n"
but got: "File \"invalid_format4.ml\", line 5, characters 20-21:\n5 |   eprintf (f_ \"%b\") 2\n                        ^\nError: This expression has type int but an expression was expected of type\n         bool\n"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:11:Compile OCaml code:4:invalid_format3.ml

error output of ocamlc -c -I ../libgettext-ocaml/ -I ../libgettext-stub-ocaml/ TestGettext.ml invalid_format3.ml
expected: "File \"invalid_format3.ml\", line 5, characters 20-21:\nError: This expression has type int but an expression was expected of type\n         string\n"
but got: "File \"invalid_format3.ml\", line 5, characters 20-21:\n5 |   eprintf (f_ \"%s\") 2\n                        ^\nError: This expression has type int but an expression was expected of type\n         string\n"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:11:Compile OCaml code:3:invalid_format2.ml

error output of ocamlc -c -I ../libgettext-ocaml/ -I ../libgettext-stub-ocaml/ TestGettext.ml invalid_format2.ml
expected: "File \"invalid_format2.ml\", line 5, characters 21-22:\nError: This expression has type int but an expression was expected of type\n         int64\n"
but got: "File \"invalid_format2.ml\", line 5, characters 21-22:\n5 |   eprintf (f_ \"%Ld\") 2\n                         ^\nError: This expression has type int but an expression was expected of type\n         int64\n"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:11:Compile OCaml code:2:invalid_format1.ml

error output of ocamlc -c -I ../libgettext-ocaml/ -I ../libgettext-stub-ocaml/ TestGettext.ml invalid_format1.ml
expected: "File \"invalid_format1.ml\", line 5, characters 21-22:\nError: This expression has type int but an expression was expected of type\n         int32\n"
but got: "File \"invalid_format1.ml\", line 5, characters 21-22:\n5 |   eprintf (f_ \"%ld\") 2\n                         ^\nError: This expression has type int but an expression was expected of type\n         int32\n"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:5:fr_FR/LC_MESSAGES/test11.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:4:fr_FR/LC_MESSAGES/test10.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:3:fr_FR/LC_MESSAGES/test4.mo

All values should be identical in [ (Camomile.Map,"Fonction simple sn_ ( singulier )") ; (Camomile.Hashtbl,"Fonction simple sn_ ( singulier )") ; (Camomile.Open,"Fonction simple sn_ ( singulier )") ; (Stub.Native,"sn_ plural") ; (Stub.Preload,"sn_ plural") ] in function GettextCompat.ngettext t' "sn_ singular" "sn_ plural" 0
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:2:fr_FR/LC_MESSAGES/test3.mo

All values should be identical in [ (Camomile.Map,"Content-Type: text/plain; charset=ISO-8859-1\nPlural-Forms: nplurals=2; plural=(n > 1);\n") ; (Camomile.Hashtbl,"Content-Type: text/plain; charset=ISO-8859-1\nPlural-Forms: nplurals=2; plural=(n > 1);\n") ; (Camomile.Open,"Content-Type: text/plain; charset=ISO-8859-1\nPlural-Forms: nplurals=2; plural=(n > 1);\n") ; (Stub.Native,"") ; (Stub.Preload,"") ] in function GettextCompat.gettext t' ""
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:1:fr_FR/LC_MESSAGES/test2.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:0:fr_FR/LC_MESSAGES/test1.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
Ran: 202 tests in: 0.17 seconds.
FAILED: Cases: 202 Tried: 202 Errors: 0 Failures: 11 Skip:  0 Todo: 0 Timeouts: 0.
```

**Comment by gildor478** [comment]
The failures seem unrelated to the PPX conversion.

Can you confirm that?
(just run the test at head maybe).

Otherwise the rest of the change looks good.

**Comment by rwmjones** [comment]
Here are the errors for OCaml 4.07 + camlp4 + ocaml-gettext + my patch "Miscellaneous changes to remove deprecated features." which is required to compile ocaml-gettext at all with recent OCaml:

```
Version         : ocaml-gettext 0.3.7
OS              : Unix
Running tests ...
.......................................................................................................................................................................................FFFFFF............F
==============================================================================
Failure: Test ocaml-gettext:11:Compile OCaml code:6:invalid_format5.ml

error output of ocamlc -c -I ../libgettext-ocaml/ -I ../libgettext-stub-ocaml/ TestGettext.ml invalid_format5.ml
expected: "File \"invalid_format5.ml\", line 5, characters 29-45:\nError: This expression has type (int64 -> 'a, 'b, 'c, 'd, 'd, 'a) format6\n       but an expression was expected of type\n         (int -> 'e, 'f, 'g, 'g, 'g, 'e) format6\n"
but got: "File \"invalid_format5.ml\", line 5, characters 29-45:\nError: This expression has type\n         (int -> 'a, int -> 'a) CamlinternalFormatBasics.precision\n       but an expression was expected of type\n         (int -> 'a, int64 -> 'b) CamlinternalFormatBasics.precision\n       Type int is not compatible with type int64 \n"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:5:fr_FR/LC_MESSAGES/test11.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:4:fr_FR/LC_MESSAGES/test10.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:3:fr_FR/LC_MESSAGES/test4.mo

All values should be identical in [ (Camomile.Map,"Fonction simple sn_ ( singulier )") ; (Camomile.Hashtbl,"Fonction simple sn_ ( singulier )") ; (Camomile.Open,"Fonction simple sn_ ( singulier )") ; (Stub.Native,"sn_ plural") ; (Stub.Preload,"sn_ plural") ] in function GettextCompat.ngettext t' "sn_ singular" "sn_ plural" 0
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:2:fr_FR/LC_MESSAGES/test3.mo

All values should be identical in [ (Camomile.Map,"Content-Type: text/plain; charset=ISO-8859-1\nPlural-Forms: nplurals=2; plural=(n > 1);\n") ; (Camomile.Hashtbl,"Content-Type: text/plain; charset=ISO-8859-1\nPlural-Forms: nplurals=2; plural=(n > 1);\n") ; (Camomile.Open,"Content-Type: text/plain; charset=ISO-8859-1\nPlural-Forms: nplurals=2; plural=(n > 1);\n") ; (Stub.Native,"") ; (Stub.Preload,"") ] in function GettextCompat.gettext t' ""
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:1:fr_FR/LC_MESSAGES/test2.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
==============================================================================
Failure: Test ocaml-gettext:6:Gettext implementation test:1:Cross check:0:fr_FR/LC_MESSAGES/test1.mo

All values should be identical in [ (Camomile.Map,"h\195\169") ; (Camomile.Hashtbl,"h\195\169") ; (Camomile.Open,"h\195\169") ; (Stub.Native,"hey") ; (Stub.Preload,"hey") ] in function GettextCompat.gettext t' "hey"
------------------------------------------------------------------------------
Ran: 202 tests in: 0.29 seconds.
FAILED: Cases: 202 Tried: 202 Errors: 0 Failures: 7 Skip:  0 Todo: 0 Timeouts: 0.
```

**Comment by gildor478** [comment]
So we are missing some "Compile OCaml code" errors, but otherwise it's OK.

Let me review your change later tonight (cannot do that while I am at work).

**Comment by gasche** [comment]
I think there is both positive and negative in this port.

The positive is that you were able to convert to ppx without changing the surface syntax for users. This is impressive (a testament to the fact that the syntax chosen in the first place was tasteful enough) and I can see how that is very useful/comfortable in term of compatibility with codebase, documentation material, etc.

The negative is that you are proposing a ppx with the same gettext syntax as before, which breaks the rules of how "good ppx extensions" are supposed to behave. The rules of a good PPX is that things that look like normal OCaml syntax should be interpreted exactly like normal OCaml syntax, without giving new and incompatible meanings to it; the parts of the program with non-standard semantics (the point of the extension) should be concentrated in extension points and attributes (attributes should be used when the new behavior is "in addition" to the standard behavior, instead of being a replacement).

In the specific case of gettext, it's very easy to see how ppx features could be used to above the criticism above: this is a use-case where extension points fit perfectly. Instead of

```ocaml
print_endline (s_ "Hello world !");
Printf.printf (f_ "Hello %s !\n") "world";
```

you would just use

```ocaml
print_endline [%gettext s "Hellow World"];
Printf.printf [%gettext f "Hello %s !\n") "world";
```

I have mixed feelings about the whole situation:

- You did a fair amount of work and the result is good, so it feels bad to complain about it now.
- Following the "good ppx principles" as suggested above breaks compatibility, so it means more work for you now and also more work for users later.
- On the other hand, I believe the rules are important.
- If I was a user of your ppx-gettext work, I would appreciate if there was one possible mode-of-use that would not break those rules.

Maybe a compromise would be to have one of:

- A transition period with a ppx extension that supports both the "legacy" camlp4 syntax and a "principled" ppx syntax (users can move to that part first, and gradually transition their code from legacy to principled mode; at some point you pull the plug off the legacy syntax).
- A transition *tool* that ports code using the legacy syntax into code using the principled syntax. It might not be too hard to extract, from your AST traverser that recognizes the legacy syntax, a list of "patches" to apply to the right positions in the original sources (using the location information in the AST) to convert to new syntax, without losing the formatting of the source code. (Re-pretty-printing the AST would break that last part.)

**Comment by rwmjones** [comment]
We have like over 100K lines of OCaml code across multiple projects all using this syntax *and* they have to remain compatible with the old and new versions of ocaml-gettext and OCaml, so changing the syntax is a non-starter.

**Comment by gildor478** [comment]
Thanks @gasche for the comment. I understand your concerns/ For now, the patch of @rwmjones fixes a real problem and I want to use it.

If you feel that something better can be done, feel free to help build another/improved ppx extension that can do what you describe.

**Pull request merged**
